# Generated by Django 4.0.1 on 2022-01-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(blank=True, max_length=16, null=True)),
                ('Age', models.CharField(blank=True, max_length=16, null=True)),
                ('Address', models.CharField(blank=True, max_length=16, null=True)),
                ('ZipCode', models.CharField(blank=True, max_length=16, null=True)),
                ('Phone', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='deposit',
            name='Amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
