# Generated by Django 3.2.11 on 2022-03-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDMS', '0004_auto_20220308_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='MAC_ID',
        ),
        migrations.AlterField(
            model_name='mac',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
